import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  maincontainer: {flex: 1,backgroundColor:'#fff'},
  title:{fontSize:15,fontWeight:'bold',color:'#383b3f'},
  activitytext:{fontSize:14},
  heading2:{margin:5,alignSelf:'stretch',padding:5,fontSize:16,fontWeight:'bold',color:'#383b3f'},
  activitycontainer:{borderWidth:1,borderColor:'#66afe9',margin:5,padding:10},
  header:{flex:1,backgroundColor:'#fff',justifyContent:'center',alignItems:'center'},
  logo:{justifyContent:'center'},
  subcontainer:{backgroundColor:'#fff',margin:10,padding:10},
  message:{color:'#2dbc10',marginBottom:15},
  input:{height:40,backgroundColor: '#fff',padding:10,marginBottom:10,borderWidth:1,borderColor:'#ccc',fontSize:16},
  textarea:{backgroundColor: '#fff',padding:3,marginBottom:10,borderWidth:1,borderColor:'#ccc',fontSize:16},
  halfinput:{height:40,backgroundColor: '#fff',padding:10,marginBottom:10,borderWidth:1,borderColor:'#ccc',fontSize:16},
  formlabel:{color:'#333'},
  smallheading:{marginBottom:6},
  transferprice:{flexDirection:'row'},
  transferpricecontainer:{flex:2},
  banklinks:{flex: 1,marginTop:10,borderColor:'#0350A2',borderWidth:1},
  currencytext:{flex:1,color:'#fff',fontWeight:'bold',textAlign: 'center'},
  topheading:{fontSize:18,marginTop:10,padding:3,color:'#ffffff',marginBottom:10,fontWeight:'bold'},
  subheadercontainer:{padding: 5,margin:8},
  footermaincontainer:{flex:1,flexDirection:'row',backgroundColor: '#fff',},
  footernav:{flex:1,paddingTop:16,borderLeftWidth:1,borderColor:'#e1e1e1' },
  footernavicon:{textAlign:'center'},
  footer:{flex:1,alignItems:'center',borderTopWidth:1,borderColor:"#e1e1e1"},
  footernavtext:{fontWeight:'bold',textAlign:'center'},
  singlepagecontainer:{padding:10,backgroundColor:'#fff',flex:1},
  transationrow:{flexDirection:'row',paddingBottom:20,paddingTop:20,borderBottomWidth:1,borderColor:'#e1e1e1'},
  transationaddressrow:{paddingBottom:20,paddingTop:20,borderBottomWidth:1,borderColor:'#e1e1e1'},
  transationlabel:{fontSize:18,flex:1,fontWeight:'bold'},
  transationtext:{flex:2,fontSize:16},
  buttonContainer:{paddingVertical:10, backgroundColor: '#337ab7',alignSelf:'stretch'},
  buttonText:{textAlign:'center',color:'#ffffff',fontWeight:'bold',fontSize:20},
  errormsg:{color:'#C12127',textAlign:'center',fontSize:16},
  parentcontainer:{flex:1,backgroundColor:'#fff'},
  addressblock:{marginTop:2,paddingBottom:10},
  subaddressblock:{flexDirection:'row',marginBottom:10},
  textcontainer:{fontSize:17},
  subheading:{alignSelf:'stretch',fontSize:18,fontWeight:'bold',color:'#383b3f',marginBottom:4},
  pageheading:{alignSelf:'stretch',fontSize:21,fontWeight:'bold',color:'#383b3f',marginBottom:4},
  labeltext:{alignSelf:'stretch',fontSize:18,marginBottom:4,fontWeight:'bold',color:'#10ADE4'},
  formtext:{color:'#333',fontSize:17,fontWeight:'bold'},
})

export default styles;
